name: New Feature request
description: Suggest an idea for this project
labels: [enhancement]
assignees: []

body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

  - type: textarea
    attributes:
      label: Describe the solution/feature you'd like to see.

  - type: textarea
    attributes:
      label: Describe alternatives you've considered.

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
