name: Kodi Matrix Repo

on:
  push:
    branches:
      - 'master'
      - 'kodi-matrix'
      - 'kodi-py3'

jobs:
  check-addon:
    name: Kodi Matrix Repository Check (Py3)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kodi-branch: [matrix]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # sudo apt-get install libxml2-utils
          python -m pip install --upgrade pip
          pip install kodi-addon-checker
      - name: Run kodi-addon-checker
        run: |
          kodi-addon-checker --branch=${{ matrix.kodi-branch }} .
